# backend/agent.py
"""
LangGraph agent exposing three tools:
 1. QuerySQLTool – natural‑language → SQL → SQLite
 2. SearchPoliciesTool – RAG over FAISS SOP index
 3. GenerateTicketTool – create markdown investigation ticket
"""
from __future__ import annotations
import os
import sqlite3
import textwrap
import json
from typing import List, Tuple, Dict, Any
from langchain_core.tools import Tool
from langchain_community.llms import Ollama  # you can swap for OpenAI, etc.
from langchain_core.prompts import PromptTemplate
from langgraph.graph import StateGraph, END
from backend.db import get_connection, search_sops

# ----------------------------------------------------------------------
# LLM (Ollama local – ensure you have `ollama run llama3` or similar)
# ----------------------------------------------------------------------
LLM = Ollama(model="llama3.2:latest")  # replace with your preferred LLM endpoint

# ----------------------------------------------------------------------
# Tool 1: QuerySQLTool
# ----------------------------------------------------------------------
def nl_to_sql(question: str) -> str:
    """Very simple prompt‑to‑SQL – for production use a dedicated SQL‑LLM."""
    prompt = PromptTemplate(
        input_variables=["question"],
        template=(
            "You are an expert SQL analyst for a telecom database. "
            "Given the question below, output a single SQLite query (no explanation).\n\n"
            "Question: {question}\n\nSQL:"
        ),
    )
    chain = prompt | LLM
    sql = chain.invoke({"question": question}).strip()
    # Remove possible markdown fences
    if sql.startswith("```"):
        sql = sql.split("```")[1]
        if sql.lower().startswith("sql"):
            sql = sql[3:].strip()
    return sql


def run_sqlite_query(sql: str) -> List[Dict]:
    conn = get_connection()
    cur = conn.cursor()
    try:
        cur.execute(sql)
        rows = cur.fetchall()
        col_names = [desc[0] for desc in cur.description]
        return [dict(zip(col_names, row)) for row in rows]
    except Exception as e:
        return [{"error": str(e)}]
    finally:
        conn.close()


query_sql_tool = Tool(
    name="QuerySQLTool",
    func=lambda q: run_sqlite_query(nl_to_sql(q)),
    description=(
        "Convert a natural language question about customer data into a SQLite query, "
        "execute it, and return the result as a list of dicts."
    ),
)

# ----------------------------------------------------------------------
# Tool 2: SearchPoliciesTool
# ----------------------------------------------------------------------
def search_policies_tool(query: str) -> List[str]:
    return search_sops(query, top_k=3)


search_policies_tool = Tool(
    name="SearchPoliciesTool",
    func=search_policies_tool,
    description=(
        "Given a natural language query, retrieve the top‑3 most relevant "
        "Standard Operating Procedure (SOP) snippets from the telecom knowledge base."
    ),
)

# ----------------------------------------------------------------------
# Tool 3: GenerateTicketTool
# ----------------------------------------------------------------------
def generate_ticket_tool(payload: str) -> str:
    """
    Expects a JSON string with keys:
      - phone: customerID
      - summary: short issue description
      - steps: list of resolution steps (optional)
    Returns markdown ticket text.
    """
    try:
        data = json.loads(payload)
    except Exception:
        data = {"raw": payload}
    cid = data.get("phone", data.get("customerID", "UNKNOWN"))
    summary = data.get("summary", "No summary provided")
    steps = data.get("steps", [])
    # Pull customer record for extra context
    conn = get_connection()
    cur = conn.cursor()
    cur.execute("SELECT * FROM customers WHERE customerID = ?", (cid,))
    row = cur.fetchone()
    conn.close()
    if row:
        cols = [desc[0] for desc in cur.description]
        cust_info = dict(zip(cols, row))
    else:
        cust_info = {}

    md = f"""# Investigation Ticket – {cid}

**Summary:** {summary}

**Customer Profile**
{json.dumps(cust_info, indent=2)}

**Recommended Steps**
"""
    if steps:
        for i, s in enumerate(steps, 1):
            md += f"{i}. {s}\n"
    else:
        md += "_No specific steps provided – refer to SOPs above._\n"

    md += "\n---\n*Ticket generated by AI‑Agent on {timestamp}*\n".format(
        timestamp=__import__("datetime").datetime.now().isoformat(timespec="seconds")
    )
    return md


generate_ticket_tool = Tool(
    name="GenerateTicketTool",
    func=generate_ticket_tool,
    description=(
        "Create a markdown investigation ticket. Input must be a JSON string "
        "containing at least 'phone' (customerID) and 'summary'. Optional 'steps' array."
    ),
)

# ----------------------------------------------------------------------
# LangGraph State & Nodes
# ----------------------------------------------------------------------
from typing import TypedDict

class AgentState(TypedDict):
    input: str
    sql_result: List[Dict]
    sop_result: List[str]
    ticket_md: str
    final_answer: str

def node_sql(state: AgentState) -> AgentState:
    res = query_sql_tool.func(state["input"])
    state["sql_result"] = res if isinstance(res, list) else [{"error": str(res)}]
    return state

def node_sop(state: AgentState) -> AgentState:
    res = search_policies_tool.func(state["input"])
    state["sop_result"] = res
    return state

def node_ticket(state: AgentState) -> AgentState:
    # Build a simple payload from the original query + sql results
    payload = {
        "phone": state["input"].split()[-1] if state["input"] else "UNKNOWN",
        "summary": state["input"],
        "steps": [f"SQL returned {len(state['sql_result'])} rows."]
        if state["sql_result"]
        else [],
    }
    state["ticket_md"] = generate_ticket_tool.func(json.dumps(payload))
    return state

def node_final(state: AgentState) -> AgentState:
    # Compose a readable answer
    sql_out = state.get("sql_result", [])
    sop_out = state.get("sop_result", [])
    parts = []
    if sql_out and not any("error" in r for r in sql_out):
        parts.append("**Data Query Result:**")
        # Format as Markdown Table
        if len(sql_out) > 0:
            keys = list(sql_out[0].keys())
            header = "| " + " | ".join(keys) + " |"
            separator = "|" + "|".join(["---"] * len(keys)) + "|"
            parts.append(header)
            parts.append(separator)
            for row in sql_out[:10]:  # limit to 10 rows
                parts.append("| " + " | ".join(str(row.get(k, "")) for k in keys) + " |")
        else:
            parts.append("_Query returned 0 rows._")
    else:
        parts.append("_No data returned or error in SQL query._")
    if sop_out:
        parts.append("\n**Relevant SOPs:**")
        for i, s in enumerate(sop_out, 1):
            parts.append(f"{i}. {s}")
    parts.append("\n**Investigation Ticket (Markdown):**")
    parts.append(state.get("ticket_md", "_Ticket not generated_"))
    state["final_answer"] = "\n".join(parts)
    return state

def build_agent():
    workflow = StateGraph(AgentState)
    workflow.add_node("sql", node_sql)
    workflow.add_node("sop", node_sop)
    workflow.add_node("ticket", node_ticket)
    workflow.add_node("final", node_final)

    workflow.set_entry_point("sql")
    workflow.add_edge("sql", "sop")
    workflow.add_edge("sop", "ticket")
    workflow.add_edge("ticket", "final")
    workflow.add_edge("final", END)

    return workflow.compile()

agent_executor = build_agent()
